export * from './Footer/script.js'
export * from './Header/script.js'
export * from './pages/Index/IndexCatalogLink/script.js'
export * from './pages/Index/IndexMain/script.js'
export * from './pages/Index/IndexSteps/script.js'
export * from './pages/PickUp/script.js'
